"""create study_sessions table

Revision ID: 31e5f8ec2dc8
Revises: a53aa7772ac6
Create Date: 2026-08-08 21:32:16.972287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e5f8ec2dc8'
down_revision = 'a53aa7772ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_subject_id'))

    op.drop_table('study_sessions')
    # ### end Alembic commands ###
