"""make filename nullable on study_materials for R2 transition

Revision ID: 93ab57defadb
Revises: d9847b686226
Create Date: 2026-08-09 18:43:52.576820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ab57defadb'
down_revision = 'd9847b686226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_key', sa.String(length=500), nullable=True))

    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key', sa.String(length=500), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_key', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_key')

    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('storage_key')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('attachment_key')

    # ### end Alembic commands ###
