"""create assignments and exams tables

Revision ID: a53aa7772ac6
Revises: a27317675d75
Create Date: 2026-08-08 15:53:47.182654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53aa7772ac6'
down_revision = 'a27317675d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('attachment_original_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_exam_date'), ['exam_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_user_id'))
        batch_op.drop_index(batch_op.f('ix_exams_subject_id'))
        batch_op.drop_index(batch_op.f('ix_exams_exam_date'))

    op.drop_table('exams')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_subject_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_due_date'))

    op.drop_table('assignments')
    # ### end Alembic commands ###
